### ISSUE TITLE
allowedUploads doesn't restrict undesired formats

### ISSUE THREAD

**Issue by EvelynTl** [ajnyga/allowedUploads#10]
**Description of issue or problem I’m having:**

 We tried limiting our allowed uploads to .docx only, but we seem to be still allowed to upload files of any format. It is the same for accounts with only author role and for accounts with editor role 

**Steps I took leading up to the issue:**
We have been using OJS (successfully) and didn't try to limit the uploads. When we did try to limit uploads, it didn't work
 

**What I tried to resolve the issue:**
@odkr tried some things, just in case, that we didn't expect to have any effect and they didn't
 
**Application Version:**

OJS: v3.3.0-10 running on a Debian v11.3 (“bullseye”) LAMP system, using

    Linux v5.10.0-9
    Apache v2.4.53
    PHP (fpm-fcgi) v7.4.28
    MariaDB v15.1

**Additional information, such as screenshots and error log messages if applicable:**

 
![restricted uploads](https://user-images.githubusercontent.com/98876806/166223697-bbc7c227-54ae-484c-b61e-8f9a93968b3a.jpg)

Thank you for looking into this!

**Comment by ajnyga** [comment]
Thanks, my plugin supports 3.2 at the moment. Probably something has changed in the way the files are uploaded and the checks the plugin does do not work anymore.

**Comment by ajnyga** [comment]
So I actually had an error with OJS 3.3.0 stable (git) and the latest version of the plugin. That error is now fixed in the current master branch and I will do a new release for it. 

I tested it manually on a local installation of 3.3.0 and seems to work. Not sure I am seeing the same problem as you were, but please check the latest release for 3.3.0.
